target_region = "europe-west1"
target_zone = "europe-west1-b"
academy_prefix = "as"
project_name = "acme-cmdb"
#project = "cw-academy-g3-quest"
project = "cw-academy-sandbox-alex"
gh_owner = "cw-alex-stangier"
gh_repo = "cw-alex-stangier/acme-cmdb"