basePath: /set_state
consumes:
- application/json
- application/json
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact: {}
  description: |-
    Tries to set the desired state on a supplied instance in a supplied zone.
    Needs a service worker JSON Key file to authenticate inside the Body.
  title: Change State of Compute Engines
  version: "1.0"
paths: {}
produces:
- application/json
- application/json
swagger: "2.0"
